version: 2
jobs:
  build:
    working_directory: ~/coravel
    docker: 
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: 
          name: test
          command: 'dotnet test .\coravel\Src\Tests\Tests.csproj'